### ISSUE TITLE
Error creating new project - Failed while installing Sightly 1.1

### ISSUE THREAD

**Issue by jgrandscrutton** [adobe/aem-eclipse-developer-tools#72] opened 2016-06-08 10:12 UTC
Using latest Eclipse, dev tools and archetype I get a "Failed while installing Sightly 1.1" error. Here's the Eclipse log info:

!ENTRY org.eclipse.m2e.logback.appender 2 0 2016-06-08 08:28:47.909
!MESSAGE Manifest com.adobe.patnersuccess:contentportal.core:bundle:0.0.1-SNAPSHOT : Unused Private-Package instructions, no such package(s) on the class path: [!*]

!ENTRY org.eclipse.m2e.logback.appender 2 0 2016-06-08 08:28:47.909
!MESSAGE Manifest com.adobe.patnersuccess:contentportal.core:bundle:0.0.1-SNAPSHOT : The JAR is empty: The instructions for the JAR named com.adobe.patnersuccess.contentportal.core did not cause any content to be included, this is likely wrong

!ENTRY org.eclipse.wst.common.project.facet.core 4 0 2016-06-08 08:28:48.379
!MESSAGE Failed while installing Sightly 1.1.
!STACK 0
java.lang.IllegalStateException: Preference node "org.eclipse.wst.validation" has been removed.
    at org.eclipse.core.internal.preferences.EclipsePreferences.checkRemoved(EclipsePreferences.java:200)
    at org.eclipse.core.internal.resources.ProjectPreferences.internalGet(ProjectPreferences.java:429)
    at org.eclipse.core.internal.preferences.EclipsePreferences.getInt(EclipsePreferences.java:585)
    at org.eclipse.wst.validation.internal.PreferencesWrapper$PreferencesWrapperPersistent.getInt(PreferencesWrapper.java:124)
    at org.eclipse.wst.validation.internal.ValPrefManagerProject.loadProjectPreferences(ValPrefManagerProject.java:204)
    at org.eclipse.wst.validation.internal.ValManager.getProjectPreferences(ValManager.java:611)
    at org.eclipse.wst.validation.internal.ValManager.getProjectPreferences(ValManager.java:592)
    at org.apache.sling.ide.eclipse.sightly.internal.SightlyFacetInstallDelegate.execute(SightlyFacetInstallDelegate.java:72)
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.callDelegate(FacetedProject.java:1477)
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modifyInternal(FacetedProject.java:441)
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.mergeChangesInternal(FacetedProject.java:1181)
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.access$2(FacetedProject.java:1117)
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProject$1.run(FacetedProject.java:324)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modify(FacetedProject.java:339)
    at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.installProjectFacet(FacetedProject.java:255)
    at org.apache.sling.ide.eclipse.core.ConfigurationHelper.convertToContentPackageProject(ConfigurationHelper.java:44)
    at org.apache.sling.ide.eclipse.m2e.internal.ContentPackageProjectConfigurator.configure(ContentPackageProjectConfigurator.java:89)
    at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:120)
    at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:501)
    at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:1)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
    at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:494)
    at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:281)
    at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:168)
    at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:1)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
    at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
    at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:136)
    at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects0(ProjectConfigurationManager.java:830)
    at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:760)
    at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$5.call(ProjectConfigurationManager.java:1)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
    at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
    at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
    at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.createArchetypeProjects(ProjectConfigurationManager.java:758)
    at org.apache.sling.ide.eclipse.ui.wizards.np.AbstractNewMavenBasedSlingApplicationWizard.createProjects(AbstractNewMavenBasedSlingApplicationWizard.java:92)
    at org.apache.sling.ide.eclipse.ui.wizards.AbstractNewSlingApplicationWizard$1.execute(AbstractNewSlingApplicationWizard.java:115)
    at org.eclipse.ui.actions.WorkspaceModifyOperation$1.run(WorkspaceModifyOperation.java:108)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
    at org.eclipse.ui.actions.WorkspaceModifyOperation.run(WorkspaceModifyOperation.java:130)
    at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:463)
    at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:371)
    at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1002)
    at org.apache.sling.ide.eclipse.ui.wizards.AbstractNewSlingApplicationWizard.performFinish(AbstractNewSlingApplicationWizard.java:111)
    at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:799)
    at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:429)
    at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
    at org.eclipse.jface.window.Window.open(Window.java:803)
    at org.eclipse.ui.actions.NewProjectAction.run(NewProjectAction.java:115)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

!ENTRY org.eclipse.m2e.logback.appender 2 0 2016-06-08 08:28:49.133
!MESSAGE Manifest com.adobe.patnersuccess:contentportal.it.tests:bundle:0.0.1-SNAPSHOT : Unused Private-Package instructions, no such package(s) on the class path: [!*]

!ENTRY org.eclipse.m2e.logback.appender 2 0 2016-06-08 08:28:49.134
!MESSAGE Manifest com.adobe.patnersuccess:contentportal.it.tests:bundle:0.0.1-SNAPSHOT : The JAR is empty: The instructions for the JAR named com.adobe.patnersuccess.contentportal.it.tests did not cause any content to be included, this is likely wrong

**Comment by jgrandscrutton** [comment] 2016-06-08 10:15
I tried removing "Sling IDE Tools - Sightly
Integration (Optional)" but I still get the same error. It appears that it might still be installed for AEM Developer Tools, but I don't have the option to uninstall it from there:

<img width="709" alt="screenshot 2016-06-08 10 45 15" src="https://cloud.githubusercontent.com/assets/5359941/15890979/404f6a36-2d6a-11e6-93a5-b6e0946d0cdc.png">

**Comment by Millertaker** [comment] 2016-09-09 21:03
Same Issue

**Comment by dutoitns** [comment] 2016-12-20 07:28
Same issue.  New to AEM but just wanted to add my observation:
I created a project and then deleted it from Eclipse and the workspace directory - I then got this error when I tried to recreate it.  So somewhere Eclipse is picking up something that obstructs the project creation that wasn't in the workspace directory.  When I create projects with new names it works 100%.

**Comment by dutoitns** [comment] 2016-12-20 07:34
On retrying the same project name for the n-th time, it actually worked.  But yeah, there is definitely something wrong here - but unfortunately I can't consistently replicate the issue.

**Comment by dutoitns** [comment] 2016-12-20 07:42
Can this be a problem with Maven itself.  Anyhoo - new to AEM so won't speculate..

**Two screenshots attached**

**First Eclipse problem stacktrace:**
Description	Resource	Path	Location	Type
C:\workspace-shoprite\mywebsite\it.tests\src\main\java\org\myorg\mywebsite\it\tests\HelloWorldModelServerSideTest.java : Unable to load compiled class: org.myorg.mywebsite.it.tests.HelloWorldModelServerSideTest (org.apache.felix:maven-scr-plugin:1.20.0:scr:generate-scr-scrdescriptor:process-classes)
![issue2](https://cloud.githubusercontent.com/assets/3661427/21342050/74e7f76e-c698-11e6-9aec-ce973e1b07ee.png)
![issue1](https://cloud.githubusercontent.com/assets/3661427/21342051/75164dc6-c698-11e6-86a3-48aa3e377f27.png)



org.apache.maven.plugin.MojoExecutionException: C:\workspace-shoprite\mywebsite\it.tests\src\main\java\org\myorg\mywebsite\it\tests\HelloWorldModelServerSideTest.java : Unable to load compiled class: org.myorg.mywebsite.it.tests.HelloWorldModelServerSideTest
	at org.apache.felix.scrplugin.mojo.SCRDescriptorMojo.execute(SCRDescriptorMojo.java:249)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.apache.felix.scrplugin.SCRDescriptorException: Unable to load compiled class: org.myorg.mywebsite.it.tests.HelloWorldModelServerSideTest
	at org.apache.felix.scrplugin.helper.ClassScanner.scanSources(ClassScanner.java:148)
	at org.apache.felix.scrplugin.SCRDescriptorGenerator.execute(SCRDescriptorGenerator.java:146)
	at org.apache.felix.scrplugin.mojo.SCRDescriptorMojo.execute(SCRDescriptorMojo.java:237)
	... 32 more
Caused by: java.lang.ClassNotFoundException: org.myorg.mywebsite.it.tests.HelloWorldModelServerSideTest
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.apache.felix.scrplugin.helper.ClassScanner.scanSources(ClassScanner.java:144)
	... 34 more
	pom.xml	/mywebsite.it.tests	line 23	Maven Build Problem

**Comment by rombert** [comment] 2016-12-21 12:32
@dutoitns - could you file a separate bug report for the issue with _Unable to load compiled class: org.myorg.mywebsite.it.tests.HelloWorldModelServerSideTest_ ?

**Comment by dutoitns** [comment] 2016-12-22 06:35
I could - but I think the problem is actually something intermittently going wrong with the Maven build.
(and I can't replicate the issue consistently)

**Comment by rombert** [comment] 2016-12-22 12:21
Right, I'm also unable to replicate this consistently, which makes debugging and fixing much harder.

**Comment by timdonovanuk** [comment] 2020-04-16 13:02
FWIW some graduates I'm training up are also getting these identical errors! They are using an older version of Eclipse, getting them to update to Eclipse 2020 to see..

**Comment by gabrielwalt** [comment] 2020-08-28 11:11
Closing this as there hasn't been activity for over a year.

**Closed by gabrielwalt** 2020-08-28 11:11 UTC

**Comment by timdonovanuk** [comment] 2020-08-28 11:39
@gabrielwalt Are you referring to Adobe investment in this plugin, because a truer statement has never been said ;)
