### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by kmurugulla** [adobe/aem-eclipse-developer-tools#60] opened 2015-12-03 19:16 UTC
Hi,

I have a maven multi module project , checked out from git , imported into eclipse . All aspects of AEM Dev tooling working except import . 

While i am trying to import /apps of my project , i see the following errors in eclipse

org.eclipse.core.runtime.CoreException: Import failed
    at org.apache.sling.ide.eclipse.ui.wizards.ImportWizard$1$1.run(ImportWizard.java:101)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
    at org.apache.sling.ide.eclipse.ui.wizards.ImportWizard$1.run(ImportWizard.java:90)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.IllegalArgumentException: Attempted to beginRule: R/, does not match outer scope rule: P/ccvault-content
    at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
    at org.eclipse.core.internal.jobs.ThreadJob.illegalPush(ThreadJob.java:134)
    at org.eclipse.core.internal.jobs.ThreadJob.push(ThreadJob.java:333)
    at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:63)
    at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:290)
    at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:118)
    at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2251)
    at org.eclipse.core.internal.resources.File.create(File.java:111)
    at org.eclipse.core.internal.resources.File.create(File.java:188)
    at org.apache.sling.ide.eclipse.ui.internal.ImportRepositoryContentAction.createFile(ImportRepositoryContentAction.java:462)
    at org.apache.sling.ide.eclipse.ui.internal.ImportRepositoryContentAction.crawlChildrenAndImport(ImportRepositoryContentAction.java:320)
    at org.apache.sling.ide.eclipse.ui.internal.ImportRepositoryContentAction.run(ImportRepositoryContentAction.java:153)
    at org.apache.sling.ide.eclipse.ui.wizards.ImportWizard$1$1.run(ImportWizard.java:96)
    ... 3 more
# 
# Env Details

eclipse.buildId=4.4.1.M20140925-0400
java.version=1.8.0_66
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/murugull/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -keyring /Users/murugull/.eclipse_keyring -showlocation

**Comment by rombert** [comment] 2015-12-07 13:48
I can't reproduce this. What exact steps did you take to import the application? What version of the AEM dev tools do you use?

**Comment by kmurugulla** [comment] 2015-12-07 16:22
@rombert : The issue seems to be with happening with this specific AEM Project that i am using dev tools with . 
AEM Dev Tools -> 1.0.6
Sling IDE Tools --> 1.0.10

The following details may help you guess whats going on ..

Step 1: I have setup an AEM project using information available at https://github.com/Adobe-Consulting-Services/lazybones-aem-templates
Step 2: Added another content project module to hold initial "authored content" , which is actually packaging and deploying content to "/content" 
Step 3:  this project is "develop" branch of my git repo and there is lots of merges already happened .
Step 4: Nothing pops out from filter.xml for either of the content projects 

Please let me know if you want more details .

**Comment by rombert** [comment] 2015-12-08 12:13
@kmurugulla what I suggestion is:

- verify if this happens on other projects, e.g. https://github.com/Adobe-Marketing-Cloud/aem-project-archetype
- if it does, please let me know the exact steps you take, e.g. where you click, what menu items you use
- if it does not, try and setup a minimal project where this happens and upload it so I can try it out myself

Thanks!

**Comment by gabrielwalt** [comment] 2020-08-28 11:10
Closing this as there hasn't been activity for over a year.

**Closed by gabrielwalt** 2020-08-28 11:10 UTC
Labels: bug
