### ISSUE TITLE
Not getting JCR Properties in Eclipse after adding AEM Dev Tools

### ISSUE THREAD

**Issue by NeLk42** [adobe/aem-eclipse-developer-tools#64] opened 2016-02-15 18:54 UTC
I know it's been mentioned a few times and all seemed to be human error, and I 'm guessing mine will be a case of human error as well, but I'm starting to go nuts here.

Installed AEM Dev Tools
<img width="870" alt="screenshot 2016-02-15 18 29 30" src="https://cloud.githubusercontent.com/assets/7836921/13057557/e88c0114-d414-11e5-8289-208b04b165c1.png">
With the Developer tools installed I created an AEM project using archetype 7, AEM perspective was working fine, I was reading the JCR properties and all, all worked fine.

I have to work with other guys so I uploaded it to github, and just to test if everything was working fine I then downloaded it and I was able to clone it no problem. But ended up with a project imported that wasn't showing any JCR properties. AEM perspective was doing nothing for me this time.

This is my .gitignore just in case you think I'm removing something important, I believe it follows [Adobe documentation](https://docs.adobe.com/docs/en/aem/6-0/develop/dev-tools/ht-projects-maven.html#How-To%20Work%20with%20JSPs)

<img width="176" alt="screenshot 2016-02-15 18 51 49" src="https://cloud.githubusercontent.com/assets/7836921/13057606/3303d244-d415-11e5-8c85-2881a78ba6d3.png">

I'm not getting the JCR properties displayed in Eclipse nor I am able to see an option inside the Properties of the apps project with AEM.

According to your documentation, Eclipse Luna is supported ( Using: Version: Luna Release (4.4.0) )

No tab or anything showing up to point it towards the jcr root folder.
<img width="1174" alt="screenshot 2016-02-15 18 47 57" src="https://cloud.githubusercontent.com/assets/7836921/13057571/f2a2266a-d414-11e5-9f33-cd67788cb11f.png">

No JCR properties displayed in any node.
<img width="1675" alt="screenshot 2016-02-15 18 59 13" src="https://cloud.githubusercontent.com/assets/7836921/13057796/5e425a92-d416-11e5-83c1-2ee59c27e6f2.png">

I can "force" the aem-angular-demo.ui.apps project to show the AEM tab by going into its properties and including a Project Facet of "Content module" like follows : 

<img width="784" alt="screenshot 2016-02-15 18 58 03" src="https://cloud.githubusercontent.com/assets/7836921/13057847/abf48a26-d416-11e5-9cd0-f7b044a6eb5d.png">

<img width="785" alt="screenshot 2016-02-15 18 58 13" src="https://cloud.githubusercontent.com/assets/7836921/13057852/b57defd8-d416-11e5-9079-4005d8a109ff.png">

And after that, the project of apps will actually display the JCR Properties 
<img width="1677" alt="screenshot 2016-02-15 19 03 10" src="https://cloud.githubusercontent.com/assets/7836921/13057870/d2412ce8-d416-11e5-80e0-bee212aef784.png">

But this workaround worries me tremendously, because the rest of the projects are not setup as per default. For example: When I create a multimodule AEM using eclipse each project has something "Faceted" 

Core and Tests are using a facet of "Bundle Module"
<img width="1325" alt="screenshot 2016-02-15 19 08 04" src="https://cloud.githubusercontent.com/assets/7836921/13057962/938d13f8-d417-11e5-8e6b-df510e68fd88.png">
<img width="1322" alt="screenshot 2016-02-15 19 07 47" src="https://cloud.githubusercontent.com/assets/7836921/13057963/938e0b14-d417-11e5-93ad-0f1a017691ca.png">

Whereas Content and Apps are using "Content Module" instead
<img width="1321" alt="screenshot 2016-02-15 19 07 35" src="https://cloud.githubusercontent.com/assets/7836921/13057978/b9e6cff8-d417-11e5-8ac4-c5cc77aaa075.png">
<img width="1371" alt="screenshot 2016-02-15 19 07 24" src="https://cloud.githubusercontent.com/assets/7836921/13057979/b9ea4ee4-d417-11e5-9759-7990030a835e.png">

I could force all those four projects to use each of those facets, but those are the things I've noticed they have different, I have the feeling that there's more going on behind scenes and that the plugin is taking care besides setting up these facets, so instead of trying to force the things I am aware of (and miss by omission the things that I am not aware of) I'd like to know what am I doing wrong when importing this project, because I've been trying for several hours now and the behaviour I'm getting is inconsistent.

From time to time after reinstalling Eclipse (and the plugin) or deleting the project and re-cloning it (I've tried with at least 4 different repos, all offer inconsistent behaviour) sometimes I'd be able to import it with an AEM tab and with the JCR properties showing (Eclipse was actually treating that project as an AEM project) but then I'd try to do the same a second later to make sure I'd found the right configuration / instalation settings / with another project and it would fail. This inconsistent behaviour is driving me nuts, can someone please point me out what am I missing? I'd like to have the certainty that every developer in my team that ends up using that repo will be able to import it with all the JCR properties loading properly.

**Comment by rombert** [comment] 2016-02-16 11:22
Thanks for the detailed report. The reason for the inconsistency is that the facet information is stored in the `.settings` directory. That one is typically included in the `.gitignore` rules and not pushed to git.

When you clone a project from git you don't receive those files and therefore the project is not defined as a content project. For bundle projects this works but it's not easy to address for content packages.

What I suggest you do is for each project, after importing from git, right-click and click on `Configure -> Convert to Content Package`. This will ensure that all the right facets and builders are configured.

**Comment by NeLk42** [comment] 2016-02-17 13:31
Converting projects to Content package will only make sense for the Content and Apps modules, the rest of them are not content and don't need access to JCR properties, right?

What about the Bundle projects, is there no need for us to convert them to Bundle Packages?

Last but not least, would you consider eventually adding the option to import AEM projects to Eclipse to properly set them up like when you create a new project instead of having to take these workarounds? It would also be interesting to add these things to the AEM Dev Tools Plugin documentation (forgive me if it has already been added but I wasn't able to find it)

**Comment by rombert** [comment] 2016-02-19 22:01
> Converting projects to Content package will only make sense for the Content and Apps modules, the rest of them are not content and don't need access to JCR properties, right?

Right

> What about the Bundle projects, is there no need for us to convert them to Bundle Packages?

No, that one is done automatically when a project has the maven-sling-plugin configured.

> Last but not least, would you consider eventually adding the option to import AEM projects to Eclipse to properly set them up like when you create a new project instead of having to take these workarounds?

Yes, that is on the roadmap. [SLING-3100](https://issues.apache.org/jira/browse/SLING-3100) has more details about it.

>  It would also be interesting to add these things to the AEM Dev Tools Plugin documentation (forgive me if it has already been added but I wasn't able to find it properly referenced to this issue of importing a project from a repo)

Agreed, I'll add them to the documentation.

**Comment by NeLk42** [comment] 2016-02-22 10:11
Ok, thanks for all your help!

**Comment by rombert** [comment] 2016-02-26 21:59
I'll close this as a dupe of #49 since it's about content packages import. The good news is that it's very likely that the next release will have this content package import ( documentation included ).

**Comment by rombert** [comment] 2016-02-26 22:02
Hm, #49 is about something else, let's reopen until the Sling issue is committed.

**Comment by kiranhsgithub** [comment] 2017-08-29 13:33
Is Eclipse Neon supported? I am able to successfully install dev tools and can sync files with AEM. But it is currently not showing JCR properties even after I navigate from "Content Navigator". 

![image](https://user-images.githubusercontent.com/7253222/29823584-131bb496-8c9d-11e7-8ba4-712f138e9827.png)

**Comment by rombert** [comment] 2017-08-29 13:35
@kiranhsgithub  - yes, that should work. Can you file a new issue about it an attach any relevant Eclipse error.log entries?

**Comment by kiranhsgithub** [comment] 2017-08-31 18:15
@rombert  thanks. Created an issue and attached logs #80

**Comment by gabrielwalt** [comment] 2020-08-28 11:10
Closing this as there hasn't been activity for over a year.

**Closed by gabrielwalt** 2020-08-28 11:10 UTC
Labels: question
